[package]
name = "type_trait"
# Keep major and minor version in sync with zvariant crate
version = "0.0.1"

description = "Type Introspection for Rust"

[[bin]]
name = "demo"
path = "bin/demo/main.rs"

[dependencies]
type_trait_derive = { path = "../type_trait_derive" }
